Description: Deploys the AWS CloudFormation Stack Cleanup lambda into an AWS account
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  ExportPrefix:
    Description: A optional unique prefix given to the export names
    Type: String
    Default: ""


Metadata:
  AWS::ServerlessRepo::Application:
    Author: Xavier Thomas
    Description: An AWS lambda that deletes AWS resources that can be called directly or used as a Custom Resource in a CloudFormation template.
    HomePageUrl: https://github.com/xavier-thomas/aws-cfn-stack-cleanup
    Labels:
      - CloudFormation
      - CustomResource
      - Cleanup
      - Cleaner
      - DevOps
      - S3
      - Cloudwatch Logs
    LicenseUrl: LICENSE
    Name: Cfn-Stack-Cleanup
    ReadmeUrl: README.md
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/xavier-thomas/aws-cfn-stack-cleanup
    SpdxLicenseId: BSD-3-Clause


Resources:
  StackCleanupLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: ./dist
      MemorySize: 128
      Timeout: 900
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
          # Allow the lambda to assume role in other accounts.
          # Replace the resource: '*' with a specific role arn if it's fixed.
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: '*'


Outputs:

  StackCleanupLambdaArn:
    Value: !GetAtt StackCleanupLambda.Arn
    Export:
      Name: !Sub ${ExportPrefix}StackCleanupLambdaArn

  StackCleanupLambdaName:
    Value: !Ref StackCleanupLambda
    Export:
      Name: !Sub ${ExportPrefix}StackCleanupLambdaName
